### ISSUE TITLE
[FEATURE REQUEST] Source Code Documentation

### ISSUE THREAD

**Issue by mathew-odwyer** [mtosoftware/FinalEngine#176]
# Description

I propose we go through each source file individually and ensure that there is enough clear and concise documentation for the first release.

## The Why

This is required because the first release will need to have sufficient and adequate source documentation to ensure that the end user knows how to use the interfaces given to them.

## The How

We should go through each file individually, use _GhostDoc_ and whatever other tools are available.

## Requirements

- Read over each source file individually, take your time and:
  - Rewrite the source code documentation.
    - Interfaces should have a `seealso` tag linked to their implementation(s).
    - Provide documentation for edge cases (what happens if you pass `null` to this function, etc)
    - Catch fine grained exceptions and provide sufficient logging and information pertaining to why an exception was thrown.
    - Spell check!
    - Provide examples that show how to use the each function or class
      - For interfaces, provide simple examples on how to roll your own if required.
    - Provide remarks and additional information where required.
  - See how the documentation looks when compiled using [SHFB](https://github.com/EWSoftware/SHFB).

Take each individually project on as it's own goal.

**Comment by softwareantics** [comment]
A good example of a well documented class:

https://github.com/softwareantics/FinalEngine/blob/develop/FinalEngine.IO/FileSystem.cs

**Comment by softwareantics** [comment]
Completed:

#184
#183

Still remaining:

- ECS
- Extensions
- Platform
- Rendering
- Runtime
