### ISSUE TITLE
[EPIC] Final Engine 2023.2.0.0

### ISSUE THREAD

**Issue by mathew-odwyer** [mtosoftware/FinalEngine#179]
# Description

This issue serves as a way to track the first release for _Final Engine_. It will consist of sub issues pertaining to what is required for the first release. The engine has been somewhat stagnant and I need to maintain focus and do what's required to get it into a somewhat functional state for the end user.

## Requirements

- #97 
- #174 
- #175 
- #182 
- #180
- #176
- #177 
- #178
- Provide additional unit testing for things that have been missed.
- Release each individual project as it's own NuGet package.
  - Provide nice README's using [this](https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/) guide.
- Fix up CI
- Fix all warnings, etc in the project.
- CodeMaid 😄
- More test coverage

## Possible Issues

TODO

**Comment by softwareantics** [comment]
Also, unit testing!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mathew-odwyer** [comment]
- Remove FinalEngine.IO from FinalEngine.Rendering - I don't think it's being used anywhere.
- seealso
	- Interface should link to their implementations if possible.
	
- public Texture2DResourceLoader(
        IFileSystem fileSystem,
        IGPUResourceFactory factory,
        IImageInvoker invoker)
		
- Pass by ref resource manager issue?

- The whole point of separating rendering, input, etc is to keep things modular and not monolithic.
	- Having rendering components with things like input components would be stupid.
	- Think about create separate projects and packages for different types of components.
	- Such as FinalEngine.Rendering.Components and FinalEngine.Input.Components
		- It might be a good idea, but I could be wrong.

- Think about how the current entity system will consider what world it is in.
	- This is a serious concern
