### ISSUE TITLE
✨ Remove Entity Component from Entity

### ISSUE THREAD

**Issue by mathew-odwyer** [mtosoftware/FinalEngine#280]
### Checklist

- [X] I have not removed the ✨ emoji from the title.
- [X] I have searched to ensure that no existing issue covers this feature request.
- [X] For maintainers: I have updated the projects and milestones if needed.

### Description

This feature aims to enhance the editor by enabling users to efficiently remove components from entities. By implementing a `RelayCommand` that adheres to the MVVM architecture, users will be able to interact with a UI element to trigger the removal of components from entities.

### Justification

Allowing users to remove components directly from the editor interface streamlines the game development process. This feature enhances the user experience by providing a method to modify entity compositions, improving productivity. Some users might not want to have a `TransformComponent` attached to each `Entity` that is created.

### Implementation Approach

**1. Create `RemoveComponentCommand`:** Create a `RemoveComponentCommand` (`RelayCommand`) that is responsible for removing a component from an `Entity`. It will likely need to name of the component as it's `CommandParameter`. This should be impleemtned in the `EntityComponentViewModel`.

**2. Required Validation:** Ensure that any component that has a `RequiredAttribute` cannot be removed from an `Entity`. This ensures that components like `TagComponent` cannot be removed. This will likely be done in a `CanRemoveComponent()` method.

**3. Create a `EntityModifiedMessage`:** Create a `EntityModifiedMessage` to notify the `EntityInspectorViewModel` to update it's shown components - or - you could pass in a `Func` parameter to `EntityComponentViewModel` that also updates the `ObservableCollection` in `EntityInspectorViewModel` to remove the component from the view.

**4. Implement `IconButton` Creation:** Develop an `IconButton` feature, acting as a simplified button integrated with an image icon. This `IconButton` will serve in conjunction with a designated _settings_ icon, allowing users to trigger a `ContextMenu` display upon activation. The `ContextMenu` will contain a `MenuItem` facilitating the removal of the desired component.

**5. Enhance `EntityComponentView`:** Upgrade the `EntityComponentView` interface to include a dedicated _settings_ `IconButton`. The _settings_ `IconButton` will reveal a `ContextMenu` upon interaction, offering users the option to remove components from the `Entity`. This action will be connected to invoking the `RemoveComponentCommand`.

**Comment by softwareantics** [comment]
Actually, it might be important to implement the memento pattern here for the following reasons:

- Adding/removing entities might be a feature that will be allowed via multiple different ways. This will allow us to centralize the following logic:
  - Adding the entity to the scene.
  - Adding the entity to the `EntityWorld`
  - Notifies the rest of the view models that will require it (scene hierarchy, etc)
    - This is a big awesome bonus so that we don't have to worry about using the weak reference messenger directly.
  - Lastly, this allows for future support of undo/redo functionality.
