### ISSUE TITLE
[BUG] Dispose State

### ISSUE THREAD

**Issue by mathew-odwyer** [mtosoftware/FinalEngine#58]
# Expected Behavior

All the methods I'm creating to change the internal state of OpenGL objects, such as [here](https://github.com/softwareantics/FinalEngine/blob/e311456844f24b3d3d4cec6e5acdcd25d09df6de/FinalEngine.Rendering.OpenGL/Pipeline/OpenGLShader.cs#L69), should be checking whether or not they are disposed before any methods are being called, right?

# Current Behavior

I'm not checking whether they've been disposed.

**Comment by KinsonDigital** [comment]
It depends if you want to have and OpenGLShader instance with the capability of "re-attaching".  And that is not wrong.  But you could just say that if it is disposed, you need to create a new instance.  That is what I would do.  I would throw exception saying it is already disposed of.  That is the point of dispose.

**Comment by mathew-odwyer** [comment]
@KinsonDigital you're probably right, once it's been disposed it shouldn't really be in a useable state, at that point you should just create a new shader.
