### ISSUE TITLE
[FEATURE REQUEST] Caching OpenGL Uniform locations

### ISSUE THREAD

**Issue by mathew-odwyer** [mtosoftware/FinalEngine#63]
# Description

Right now the OpenGL Pipeline is getting uniform locations using `glGetUniformLocation`, which can be fairly slow and hang a little. I think it would be a good idea to cache uniform locations as they're retrieved.

## The Why

This would be necessary to increase speed and overall performance of the OpenGL back-end.

## The How

Simply using a `Dictionary<string, int>` which stores the name of the location (key) and the location (value).

**Comment by KinsonDigital** [comment]
I did this as well for the same reasons.  😌

**Comment by mathew-odwyer** [comment]
Makes me feel like I'm making right decisions lol

**Comment by mathew-odwyer** [comment]
Fixed by #65
